language: bash
services: docker

before_install:
  - docker network create -d bridge rijanet
  - docker run -d --name rijamysql --net=rijanet --env MYSQL_ROOT_PASSWORD=changemeroot --env MYSQL_DATABASE=wordpress --env MYSQL_USER=wordpress --env MYSQL_PASSWORD=changemeuser mysql:5.5.45
  - RIJAMYSQL=$(docker inspect -f '{{.Config.Hostname }}' rijamysql)
  - echo "$RIJAMYSQL"

script:
  - docker build -t rija/docker-nginx-fpm-caches-wordpress .
  - docker run --privileged -d --name rijaweb --net=rijanet --env SERVER_NAME=dockerfiletest.cinecinetique.com --env DB_HOSTNAME=$RIJAMYSQL --env DB_USER=wordpress --env DB_PASSWORD=changemeuser --env DB_DATABASE=wordpress --env GIT_SSH_URL=https://github.com/WordPress/WordPress.git -v /etc/letsencrypt:/etc/letsencrypt -v /var/run/docker.sock:/var/run/docker.sock -p 443:443 -p 80:80 rija/docker-nginx-fpm-caches-wordpress
  - docker exec -it rijaweb bash -c "letsencrypt certonly --help"
  - sleep 15
  - docker exec -it rijaweb bash -c "test -f /tmp/last_bootstrap"
  - docker exec -it rijaweb bash -c "cat /etc/hosts"
  - docker exec -it rijaweb bash -c "cat /etc/letsencrypt/cli.ini"
  - sleep 10
  - docker exec -it rijaweb bash -c "ps -e"
  - docker exec -it rijaweb bash -c "ps -e" | grep "supervisor"
  - docker exec -it rijaweb bash -c "ps -e" | grep "nginx"
  - docker exec -it rijaweb bash -c "ps -e" | grep "php-fpm7.1"
  - docker exec -it rijaweb bash -c "ps -e" | grep "cron"
  - docker exec -it rijaweb bash -c "curl --head http://dockerfiletest.cinecinetique.com"
  - docker exec -it rijaweb bash -c "curl --head http://dockerfiletest.cinecinetique.com" | grep 301
  - sleep 20
  - docker exec -it rijaweb bash -c "cat /usr/share/nginx/www/wp-config.php"
  - docker exec -it rijaweb bash -c "ls -alrt /usr/share/nginx/www/" | grep "wp-content"

after_failure:
  - docker exec -it rijaweb bash -c "supervisorctl tail bootstrap"
  - docker logs rijaweb
