version: '2'
services:
  webapp:
    restart: 'unless-stopped'
    cap_add:
      - NET_ADMIN
    networks:
      - wp_net
    image: ${REGISTRY_URL}/${IMAGE_NAME}:${VERSION}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp:/root/sql
    ports:
      - 443:443
      - 80:80
    depends_on:
      - db
    environment:
      SERVER_NAME:
      ADMIN_EMAIL:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_HOSTNAME: dbs
      DB_USER: ${WP_DB_USER}
      DB_PASSWORD: ${WP_DB_PASSWORD}
      DB_DATABASE: ${WP_DB_NAME}
    links:
      - db:dbs
  db:
    restart: 'unless-stopped'
    networks:
      - wp_net
    image: mariadb:10.2
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}

networks:
  wp_net:
    driver: bridge

volumes:
  mariadb_data:
