version: '2'
services:
  web:
    restart: 'always'
    networks:
      - wp_net
    image: rija/docker-nginx-fpm-caches-wordpress
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /${HOME}/.ssh:/root/deploykeys:ro
      - /${HOME}/Downloads:/root/backups
    ports:
      - 443:443
      - 80:80
    depends_on:
      - db
    environment:
      GIT_DEPLOY_KEY: ${GIT_DEPLOY_KEY}
      SERVER_NAME:
      ADMIN_EMAIL:
      DB_HOSTNAME: dbs
      DB_USER: ${WP_DB_USER}
      DB_PASSWORD: ${WP_DB_PASSWORD}
      DB_DATABASE: ${WP_DB_NAME}
    links:
      - db:dbs
  db:
    networks:
      - wp_net
    image: mariadb:10.2
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}

networks:
  wp_net:
    driver: bridge

volumes:
  mariadb_data:
